DROP TABLE IF EXISTS threads CASCADE;

CREATE TABLE threads (
  id SERIAL PRIMARY KEY NOT NULL,
  parent_tweet INTEGER REFERENCES tweets(id) ON DELETE CASCADE,
  reply_author INTEGER REFERENCES users(id) ON DELETE CASCADE,
  reply VARCHAR(255) NOT NULL,
  created_on TIMESTAMP DEFAULT NOW()
);

